import { Category, Product, Promotion, Order, Reservation, RestaurantConfig } from './types';

export const initialCategories: Category[] = [
  { id: 'cat-1', name: 'Platos Tradicionales', order: 1, active: true },
  { id: 'cat-2', name: 'Sopas', order: 2, active: true },
  { id: 'cat-3', name: 'Desayunos y Bocados', order: 3, active: true },
  { id: 'cat-4', name: 'Bebidas Tradicionales', order: 4, active: true },
  { id: 'cat-5', name: 'Postres', order: 5, active: true },
];

export const initialProducts: Product[] = [
  {
    id: 'prod-1',
    name: 'Mondongo Chuquisaqueño',
    description: 'Costillas de cerdo doradas cocidas lentamente en salsa de ají colorado y ají amarillo criollo, servido con mote de maíz amarillo pelado y papas cocidas.',
    price: 45,
    available: true,
    categoryId: 'cat-1',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop',
    featured: true,
  },
  {
    id: 'prod-2',
    name: 'Chorizo Chuquisaqueño',
    description: 'Tradicionales chorizos criollos artesanales sazonados con hierbabuena y especias locales. Acompañados de pan, ensalada fresca de cebolla y tomate con quilquiña, y escabeche.',
    price: 35,
    available: true,
    categoryId: 'cat-1',
    image: 'https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=600&auto=format&fit=crop',
    featured: true,
  },
  {
    id: 'prod-3',
    name: 'Sopa de Maní Tradicional',
    description: 'La reina de las sopas bolivianas: caldo concentrado de carne de res con base de maní blanco molido y tierno, servido con fideos gruesos, papas picadas y crujientes papas al hilo.',
    price: 25,
    available: true,
    categoryId: 'cat-2',
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600&auto=format&fit=crop',
    featured: true,
  },
  {
    id: 'prod-4',
    name: 'Karapecho Chuquisaqueño',
    description: 'Deliciosos bocados de charque de res (carne deshidratada al sol) fritos hasta quedar crocantes, acompañados de mote de maíz blanco y papas con cáscara doradas.',
    price: 40,
    available: true,
    categoryId: 'cat-1',
    image: 'https://images.unsplash.com/photo-1603048588665-791ca8aea617?w=600&auto=format&fit=crop',
    featured: false,
  },
  {
    id: 'prod-5',
    name: 'Ckoqo de Pollo',
    description: 'Guiso tradicional de pollo tierno cocido en salsa aromática de ajíes chuquisaqueños, vino tinto de mesa y chicha criolla, acompañado de papa y mote.',
    price: 38,
    available: true,
    categoryId: 'cat-1',
    image: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=600&auto=format&fit=crop',
    featured: false,
  },
  {
    id: 'prod-6',
    name: 'Empanadas de Santa Clara',
    description: 'Delicada empanada de masa quebrada dulce rellena de un picadillo jugoso de pollo con pasas, huevo duro, aceituna y un toque sutil de canela y azúcar glas.',
    price: 12,
    available: true,
    categoryId: 'cat-3',
    image: 'https://images.unsplash.com/photo-1608756687911-a15100ba3c71?w=600&auto=format&fit=crop',
    featured: true,
  },
  {
    id: 'prod-7',
    name: 'Tojori Caliente con Pastel',
    description: 'Bebida espesa y reconfortante a base de maíz wilcaparo molido, cocido con leche, canela, clavo de olor y cáscara de naranja, acompañado de un pastel inflado con queso.',
    price: 15,
    available: true,
    categoryId: 'cat-3',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&auto=format&fit=crop',
    featured: false,
  },
  {
    id: 'prod-8',
    name: 'Refresco de Mocochinchi',
    description: 'Refrescante bebida de duraznos deshidratados enteros cocidos a fuego lento con azúcar caramelizada, canela, clavo de olor, servido helado con su durazno.',
    price: 8,
    available: true,
    categoryId: 'cat-4',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop',
    featured: false,
  },
  {
    id: 'prod-9',
    name: 'Chicha de Maíz Chuquisaqueña',
    description: 'Bebida ancestral fermentada de maíz, ligeramente dulce, aromática y muy refrescante para acompañar platos picantes.',
    price: 12,
    available: true,
    categoryId: 'cat-4',
    image: 'https://images.unsplash.com/photo-1528498033373-3c6c08e93d79?w=600&auto=format&fit=crop',
    featured: false,
  },
  {
    id: 'prod-10',
    name: 'Helado Artesanal de Canela',
    description: 'Helado batido a mano con canela pura seleccionada, refrescante, digestivo e ideal para cerrar con broche de oro un almuerzo tradicional.',
    price: 10,
    available: true,
    categoryId: 'cat-5',
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600&auto=format&fit=crop',
    featured: false,
  },
];

export const initialPromotions: Promotion[] = [
  {
    id: 'promo-1',
    name: 'Combo Tradición Chuquisaqueña',
    description: '¡El verdadero sabor de Sucre en Cochabamba! Incluye 1 plato de Mondongo Chuquisaqueño, 1 porción de Sopa de Maní Tradicional y 1 Refresco de Mocochinchi frío.',
    originalPrice: 78,
    promoPrice: 65,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop',
    startDate: '2026-07-01',
    endDate: '2026-08-31',
    active: true,
    productIds: ['prod-1', 'prod-3', 'prod-8'],
  },
  {
    id: 'promo-2',
    name: 'Dúo de Chorizos Criollos',
    description: 'Ideal para compartir en pareja. Incluye 2 abundantes platos de Chorizo Chuquisaqueño y 2 vasos helados de Chicha de Maíz Tradicional.',
    originalPrice: 94,
    promoPrice: 79,
    image: 'https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=600&auto=format&fit=crop',
    startDate: '2026-07-10',
    endDate: '2026-08-15',
    active: true,
    productIds: ['prod-2', 'prod-9'],
  },
];

export const initialOrders: Order[] = [
  {
    id: 'PED-5491',
    clientName: 'Alejandro Mendoza',
    phone: '71234567',
    type: 'delivery',
    address: 'Av. América Oeste #1420, Edificio Los Pinos, depto 4B',
    reference: 'Frente al supermercado IC Norte, portón de rejas negras',
    paymentMethod: 'qr',
    observations: 'Por favor, enviar cubiertos descartables. Mondongo bien picante.',
    items: [
      {
        id: 'item-1',
        itemType: 'product',
        itemId: 'prod-1',
        name: 'Mondongo Chuquisaqueño',
        price: 45,
        image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop',
        quantity: 1,
        observations: 'Bien picante por favor',
      },
      {
        id: 'item-2',
        itemType: 'product',
        itemId: 'prod-8',
        name: 'Refresco de Mocochinchi',
        price: 8,
        image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop',
        quantity: 2,
        observations: 'Con harto hielo',
      },
    ],
    total: 61, // 45 + 16
    date: '2026-07-11',
    time: '12:30',
    status: 'En preparación',
  },
  {
    id: 'PED-5492',
    clientName: 'María Reneé Vargas',
    phone: '60781234',
    type: 'pickup',
    address: '',
    reference: '',
    paymentMethod: 'cash',
    observations: 'Recogeré puntual a la 1:15 pm.',
    items: [
      {
        id: 'item-3',
        itemType: 'promotion',
        itemId: 'promo-1',
        name: 'Combo Tradición Chuquisaqueña',
        price: 65,
        image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop',
        quantity: 1,
        observations: 'Sopa de maní con papitas extras si se puede',
      },
    ],
    total: 65,
    date: '2026-07-11',
    time: '13:00',
    status: 'Confirmado',
  },
  {
    id: 'PED-5489',
    clientName: 'Carlos Siles Ortiz',
    phone: '77490123',
    type: 'delivery',
    address: 'Calle España #350, Zona Central',
    reference: 'A media cuadra de la Plaza 14 de Septiembre, casa colonial color naranja',
    paymentMethod: 'cash',
    observations: 'Cambio de 100 Bs por favor.',
    items: [
      {
        id: 'item-4',
        itemType: 'product',
        itemId: 'prod-2',
        name: 'Chorizo Chuquisaqueño',
        price: 35,
        image: 'https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=600&auto=format&fit=crop',
        quantity: 2,
        observations: 'Sin cebolla en el escabeche',
      },
    ],
    total: 70,
    date: '2026-07-10',
    time: '14:15',
    status: 'Entregado',
  },
];

export const initialReservations: Reservation[] = [
  {
    id: 'RES-101',
    clientName: 'Fernando Beltrán',
    phone: '72298765',
    date: '2026-07-11',
    time: '13:00',
    peopleCount: 4,
    tableAssigned: 'Mesa 2',
    comments: 'Almuerzo familiar de cumpleaños. Mesa cerca a la ventana si es posible.',
    status: 'Confirmada',
  },
  {
    id: 'RES-102',
    clientName: 'Gabriela Villarroel',
    phone: '70345612',
    date: '2026-07-11',
    time: '14:30',
    peopleCount: 2,
    tableAssigned: 'Mesa 5',
    comments: 'Ninguno.',
    status: 'Pendiente',
  },
  {
    id: 'RES-103',
    clientName: 'Roberto Lizarazu',
    phone: '65321098',
    date: '2026-07-12',
    time: '12:00',
    peopleCount: 6,
    tableAssigned: 'Mesa 1',
    comments: 'Reunión de exalumnos de Sucre.',
    status: 'Confirmada',
  },
];

export const initialRestaurantConfig: RestaurantConfig = {
  name: 'El Chuquisaqueño',
  description: 'Traemos a Cochabamba el auténtico, inconfundible y tradicional sabor chuquisaqueño. Platos abundantes elaborados con ajíes puros traídos directamente de Sucre y el toque de cariño familiar.',
  address: 'Calle Melchor Urquidi #1248, entre Av. Uyuni y Av. América (Zona Queru Queru)',
  city: 'Cochabamba, Bolivia',
  phone: '+59162418191',
  hours: 'Todos los días de 8:00 a. m. a 6:00 p. m.',
  deliveryCost: 10,
  minOrder: 20,
  prepTime: '20 - 35 min',
  socialFacebook: 'https://facebook.com/elchuquisaqueno.cbba',
  socialInstagram: 'https://instagram.com/elchuquisaqueno.cbba',
  logo: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=200&auto=format&fit=crop',
  heroImage: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=1200&auto=format&fit=crop',
  paymentMethods: ['Pago QR coordinado por WhatsApp', 'Efectivo al recibir/recoger'],
  tablesCount: 6,
};
